server:
  port: 8091
spring:
  application:
    name: seller-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://bd7r19qvtk7tt1lvek1y-mysql.services.clever-cloud.com:3306/bd7r19qvtk7tt1lvek1y
    username: ubxiszuulujhdmwq
    password: Fa3qjThlhOvnDB7CD4eg
  jpa:
    hibernate:
      ddl-auto: update
