# Eureka Client and run any port that is available as we are not defining specific port.
server:
  port: 0

# Eureka Server
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: seller-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://bspdrvyuddkd6dxjrrhc-mysql.services.clever-cloud.com:3306/bspdrvyuddkd6dxjrrhc
    username: u60ab7f3sfxsecfe
    password: a5FzjXrDHSzJzRxob54z
  jpa:
    hibernate:
      ddl-auto: update
