server:
  port: 8092
spring:
  application:
    name: inventory-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://babegyfhtjsyrtl2eyqy-mysql.services.clever-cloud.com:3306/babegyfhtjsyrtl2eyqy
    username: ujg7zjxpullmetps
    password: JJrNGjy0pRa6kH9F8s7d
  jpa:
    hibernate:
      ddl-auto: update
