# To Register as Eureka Client with Eureka Server
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: https://eureka:password@e-comm-j1pe.onrender.com/eureka
server:
  port: 8080

logging:
  level:
    root: info
    org.springframework.cloud.gateway.route.RouteDefinitionLocator: info
    org.springframework.cloud.gateway: trace

# Spring Cloud Gateway
spring:
  application:
    name: api-gateway-service

# Spring Cloud Gateway Routes
  cloud:
    gateway:

      # Seller Service Route
      routes[0]:
        id: seller-service
        uri: http://localhost:8081/seller-service
#        uri: lb://seller-service
        predicates[0]: Path=/api/seller/**

      # Order Service Route
      routes[1]:
        id: order-service
        uri: lb://order-service
        predicates[0]: Path=/api/order/**
        predicates[1]: Path=/api/order

      # Discovery Server Route
      routes[2]:
        id: discovery-server
        uri: https://e-comm-j1pe.onrender.com
        predicates[0]: Path=/eureka/web
        filters[0]: SetPath=/

      # Discovery Server Static Resources Route
      routes[3]:
        id: discovery-server-static
        uri: https://e-comm-j1pe.onrender.com
        predicates[0]: Path=/eureka/**

# Spring Data R2DBC
  r2dbc:
    url: r2dbc:mysql://bd7r19qvtk7tt1lvek1y-mysql.services.clever-cloud.com:3306/bd7r19qvtk7tt1lvek1y
    username: ubxiszuulujhdmwq
    password: Fa3qjThlhOvnDB7CD4eg
    pool:
      initial-size: 5
      max-size: 20
      max-idle-time: 30m
      validation-query: SELECT 1